# Generated by Django 6.0 on 2025-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Marque para liberar funcionalidades premium.', verbose_name='Usuário PRO'),
        ),
    ]
