# Generated by Django 6.0 on 2025-12-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_pro',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pro_legacy',
            field=models.BooleanField(default=False, verbose_name='PRO Manual (Legado)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pro_expiry_date',
            field=models.DateField(blank=True, help_text='O usuário é PRO até esta data (inclusive).', null=True, verbose_name='Expira em'),
        ),
    ]
