# Generated by Django 6.0 on 2026-01-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_pro_customuser_is_pro_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Meta Diária'),
        ),
    ]
