# Generated by Django 6.0 on 2026-01-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_daily_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_type',
            field=models.CharField(blank=True, choices=[('RIDESHARE', 'Motorista de App (Uber/99)'), ('DELIVERY', 'Entregador (Moto/Bike)'), ('BOTH', 'Ambos')], max_length=20, null=True, verbose_name='Tipo de Trabalho'),
        ),
    ]
