# Generated by Django 6.0 on 2025-12-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título Interno')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner')),
                ('link', models.URLField(verbose_name='Link de Destino (Afiliado)')),
                ('position', models.CharField(choices=[('DASHBOARD_TOP', 'Topo do Dashboard'), ('DASHBOARD_BOTTOM', 'Rodapé do Dashboard'), ('SIDEBAR', 'Menu Lateral')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
