# Generated by Django 6.0 on 2025-12-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel'), ('GNV', 'GNV'), ('ELETRICO', 'Elétrico'), ('FLEX', 'Flex')], default='FLEX', max_length=10, verbose_name='Combustível'),
        ),
    ]
