# Generated by Django 6.0 on 2025-12-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=100, verbose_name='Título Interno')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner')),
                ('link', models.URLField(verbose_name='Link de Destino (Afiliado)')),
                ('position', models.CharField(choices=[('DASHBOARD_TOP', 'Topo do Dashboard')], default='DASHBOARD_TOP', max_length=20)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Banner de Publicidade',
                'verbose_name_plural': 'Banners de Publicidade',
            },
        ),
    ]
