# Generated by Django 6.0 on 2025-12-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='clicks',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
