# Generated by Django 6.0 on 2025-12-18 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='Data do Registro')),
                ('start_km', models.PositiveIntegerField(verbose_name='Km Inicial')),
                ('end_km', models.PositiveIntegerField(verbose_name='Km Final')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ganhos Totais')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custos Totais')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Registro Diário',
                'verbose_name_plural': 'Registros Diários',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
