# Generated by Django 6.0 on 2025-12-18 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('vehicles', '0002_vehicle_fuel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(verbose_name='Data')),
                ('odometer', models.PositiveIntegerField(verbose_name='KM no momento')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('type', models.CharField(choices=[('OIL', 'Troca de Óleo'), ('TIRES', 'Pneus'), ('MECHANIC', 'Mecânica Geral'), ('ELECTRICAL', 'Elétrica'), ('DOCUMENTATION', 'Documentação/IPVA'), ('CLEANING', 'Estética/Limpeza Pesada'), ('OTHER', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição/Oficina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-date'],
            },
        ),
    ]
