# Generated by Django 6.0 on 2025-12-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='end_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Km Final'),
        ),
    ]
