# Generated by Django 6.0 on 2025-12-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_category_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_fuel',
            field=models.BooleanField(default=False, verbose_name='É Combustível?'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_maintenance',
            field=models.BooleanField(default=False, verbose_name='É Manutenção?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='actual_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM no Momento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Litros (Combustível)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='next_due_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Próxima Troca (Km)'),
        ),
    ]
