# Generated by Django 6.0 on 2026-01-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_category_is_fuel_category_is_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_mirror', to='operations.transaction', verbose_name='Transação de Origem'),
        ),
    ]
