# Generated by Django 6.0 on 2026-01-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_maintenance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_full_tank',
            field=models.BooleanField(default=False, verbose_name='Tanque Cheio?'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('OIL', 'Troca de Óleo'), ('TIRES', 'Pneus'), ('MECHANICAL', 'Mecânica Geral'), ('ELECTRICAL', 'Elétrica'), ('DOCUMENTATION', 'Documentação/IPVA'), ('CLEANING', 'Estética/Limpeza Pesada'), ('OTHER', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
    ]
