# Generated by Django 6.0 on 2026-01-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_transaction_is_full_tank_alter_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='next_due_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Próxima Troca (Km)'),
        ),
    ]
